Add helper for parsing RFC2253 Distinguished Names
thorgate/django-esteid pull request #17
Opened 2017-11-20 14:15 UTC by Jyrno42

- Move `Signer.parse_common_name` to helpers module

fixes #11

2017-11-21 08:48 UTC, simonschmidt requested changes

2017-11-21 08:48 UTC, simonschmidt commented on tests/distinguished_name.py
> +    print('expected', expected_res)
-

2017-11-21 08:48 UTC, Jyrno42 commented on tests/distinguished_name.py
> +    print('expected', expected_res)
whoops

2017-11-22 07:37 UTC, simonschmidt approved these changes

2017-11-22 07:38 UTC, merged